CREATE TABLE employees (
    emp_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR2(50),
    last_name VARCHAR2(50),
    salary NUMBER(10, 2)
);

INSERT INTO employees (first_name, last_name, salary) VALUES ('John', 'Doe', 50000);
INSERT INTO employees (first_name, last_name, salary) VALUES ('Jane', 'Smith', 60000);

COMMIT;
