import pytest
from pro.sync import diff_provided_schema_to_db
from models import ConnectionConfig, TableSchema, ColumnInfo
from database import get_engine
from sqlalchemy import create_engine, text

def test_diff_provided_schema_to_db(tmp_path):
    # Setup a mock SQLite database with one table
    db_path = str(tmp_path / "target.db")
    engine = create_engine(f"sqlite:///{db_path}")
    with engine.connect() as conn:
        conn.execute(text("CREATE TABLE users (id INTEGER PRIMARY KEY, name TEXT)"))
        conn.commit()

    config = ConnectionConfig(id="test_target", name="TargetDB", type="sqlite", database="target.db", filepath=db_path)

    # Define a desired schema (Visual Model) where:
    # 1. 'users' has an extra 'email' column
    # 2. 'products' is a brand new table
    desired_schema = [
        TableSchema(
            name="users",
            columns=[
                ColumnInfo(name="id", type="INTEGER", primary_key=True, nullable=False),
                ColumnInfo(name="name", type="TEXT", primary_key=False, nullable=True),
                ColumnInfo(name="email", type="VARCHAR(255)", primary_key=False, nullable=True)
            ],
            foreign_keys=[]
        ),
        TableSchema(
            name="products",
            columns=[
                ColumnInfo(name="id", type="INT", primary_key=True, nullable=False),
                ColumnInfo(name="price", type="DECIMAL", primary_key=False, nullable=True)
            ],
            foreign_keys=[]
        )
    ]

    # Run the diff
    result = diff_provided_schema_to_db(desired_schema, config)

    assert "sql_text" in result
    sql = result["sql_text"].lower()
    
    # Verify expected changes are detected
    assert "alter table users add column email" in sql
    assert "create table products" in sql
    assert "generated by sqlforge forward engineering" in sql

if __name__ == "__main__":
    pytest.main([__file__])
